blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a Question
    url: https://github.com/ConsulbitDev/billiard-training-fe/discussions
    about: For general questions, use GitHub Discussions instead of issues.
